---
author: "University of Melbourne Centre for Cancer Research"
date: "`r format(Sys.time(), '%a %Y-%b-%d %H:%M')`"
output:
  html_document:
    code: hide
    theme: cosmo
    toc: true
    code_download: true
  rmdformats::material:
    highlight: kate
params:
  genome: "hg38"
  maf: "/path/to/sample.maf"
  sample: "SAMPLE"
title: "`r glue::glue('sigminer results for {params$sample}')`"
description: "sigminer Results"
---

<style type="text/css">
.main-container {
  max-width: 1400px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup_knitr, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

```{r render_report_interactively, eval=F, echo=F}
params <- function(x) {
  paths <- list(
    local = list(
      sample = "SEQCII50",
      maf = here::here("inst/extdata/umccrise/v0.18/maf/SEQCII50.maf.gz"),
      genome = "hg38"
    )
  )
  paths[[x]]
}
params <- params("local")

render_me <- function() {
  rmarkdown::render(
    input = here::here("inst/rmd/wgs/signatures/sigminer.Rmd"),
    params = params)
}
render_me()
```

```{r setup}
require(Biostrings)
require(BSgenome.Hsapiens.UCSC.hg19)
require(BSgenome.Hsapiens.UCSC.hg38)
require(dplyr)
require(DT)
require(gpgr)
require(gt)
require(here)
require(kableExtra)
require(maftools)
require(NMF)
require(sigminer)
```

```{r check_params}
stopifnot(params$genome %in% c("hg19", "hg38"))
genome <- paste0("BSgenome.Hsapiens.UCSC.", params$genome)
stopifnot(file.exists(params$maf))
```

## Introduction

Here we are using
[sigminer](https://github.com/ShixiangWang/sigminer) to fit COSMIC v3 somatic
signatures.

## Analysis

* Step 1: Read MAF file

```{r read_maf}
maf <- sigminer::read_maf(params$maf, verbose = FALSE)
```

* Step 2: Tally components

```{r tally}
tally <- sigminer::sig_tally(
  maf,
  ref_genome = genome,
  mode = "ALL"
)
```

* Step 3: Fit signatures

```{r sig_fit}
if (!is.null(tally$SBS_96)) {
  SBS <- sigminer::sig_fit(t(tally$SBS_96), sig_index = "ALL", sig_db = "SBS")
  SBS_legacy <- sigminer::sig_fit(t(tally$SBS_96), sig_index = "ALL", sig_db = "legacy")
} else {
  SBS <- matrix("NO_SBS", dimnames = list(c("ROW1"), c(params$sample)))
  SBS_legacy <- matrix("NO_SBS", dimnames = list(c("ROW1"), c(params$sample)))
}

if (!is.null(tally$DBS_78)) {
  DBS <- sigminer::sig_fit(t(tally$DBS_78), sig_index = "ALL", sig_db = "DBS")
} else {
  DBS <- matrix("NO_DBS", dimnames = list(c("ROW1"), c(params$sample)))
}

if (!is.null(tally$ID_83)) {
  ID <- sigminer::sig_fit(t(tally$ID_83), sig_index = "ALL", sig_db = "ID")
} else {
  ID <- matrix("NO_ID", dimnames = list(c("ROW1"), c(params$sample)))
}
```

## Results

```{r tables}
SBS_tab <-
  tibble::as_tibble(SBS, rownames = "Sig") %>%
  dplyr::rename(Value = X) %>%
  dplyr::arrange(dplyr::desc(Value)) %>%
  dplyr::mutate(Prop = round(Value / sum(Value), 3),
                Value = round(Value, 0)) %>%
  dplyr::slice_head(n = 5)

SBS_legacy_tab <-
  tibble::as_tibble(SBS_legacy, rownames = "Sig") %>%
  dplyr::rename(Value = X) %>%
  dplyr::arrange(dplyr::desc(Value)) %>%
  dplyr::mutate(Prop = round(Value / sum(Value), 3),
                Value = round(Value, 0)) %>%
  dplyr::slice_head(n = 5)

DBS_tab <-
  tibble::as_tibble(DBS, rownames = "Sig") %>%
  dplyr::rename(Value = X) %>%
  dplyr::arrange(dplyr::desc(Value)) %>%
  dplyr::mutate(Prop = round(Value / sum(Value), 3),
                Value = round(Value, 0)) %>%
  dplyr::slice_head(n = 5)

ID_tab <-
  tibble::as_tibble(ID, rownames = "Sig") %>%
  dplyr::rename(Value = X) %>%
  dplyr::arrange(dplyr::desc(Value)) %>%
  dplyr::mutate(Prop = round(Value / sum(Value), 3),
                Value = round(Value, 0)) %>%
  dplyr::slice_head(n = 5)

knitr::kable(SBS_tab, caption = "SBS (COSMIC v3)") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left")
knitr::kable(SBS_legacy_tab, caption = "SBS (COSMIC v2)") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left")
knitr::kable(DBS_tab, caption = "DBS") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left")
knitr::kable(ID_tab, caption = "ID") %>%
  kableExtra::kable_styling(full_width = FALSE, position = "left")
```


```{r plots}
show_catalogue(t(tally$SBS_96), style = "cosmic", x_label_angle = 90, mode = "SBS") +
  ggplot2::ggtitle("SBS Plot")
show_catalogue(t(tally$DBS_78), style = "cosmic", x_label_angle = 90, mode = "DBS") +
  ggplot2::ggtitle("DBS Plot")
show_catalogue(t(tally$ID_83), style = "cosmic", x_label_angle = 90, mode = "ID") +
  ggplot2::ggtitle("ID Plot")
```

