# Generated by roxytest: Do not edit by hand!

# File R/linx.R: @testexamples

test_that("Function linx_svs_read() @ L237", {
  
  x <- system.file("extdata/linx/tables/linx.svs.tsv.gz", package = "gpgr")
  (l <- linx_svs_read(x))
  expect_equal(colnames(l)[ncol(l)], "localTICountEnd")
})


test_that("Function linx_breakend_read() @ L255", {
  
  x <- system.file("extdata/linx/tables/linx.breakend.tsv.gz", package = "gpgr")
  (l <- linx_breakend_read(x))
  expect_equal(colnames(l)[ncol(l)], "junctionCopyNumber")
})


test_that("Function linx_clusters_read() @ L273", {
  
  x <- system.file("extdata/linx/tables/linx.clusters.tsv.gz", package = "gpgr")
  (l <- linx_clusters_read(x))
  expect_equal(colnames(l)[ncol(l)], "clusterDesc")
})


test_that("Function linx_links_read() @ L291", {
  
  x <- system.file("extdata/linx/tables/linx.links.tsv.gz", package = "gpgr")
  (l <- linx_links_read(x))
  expect_equal(colnames(l)[ncol(l)], "ecDna")
})


test_that("Function linx_fusion_read() @ L309", {
  
  x <- system.file("extdata/linx/tables/linx.fusion.tsv.gz", package = "gpgr")
  (l <- linx_fusion_read(x))
  expect_equal(colnames(l)[ncol(l)], "junctionCopyNumber")
})


test_that("Function linx_drivercatalog_read() @ L327", {
  
  x <- system.file("extdata/linx/tables/linx.driver.catalog.tsv.gz", package = "gpgr")
  (l <- linx_drivercatalog_read(x))
  expect_equal(colnames(l)[ncol(l)], "maxCopyNumber")
})


test_that("Function linx_drivers_read() @ L345", {
  
  x <- system.file("extdata/linx/tables/linx.drivers.tsv.gz", package = "gpgr")
  (l <- linx_drivers_read(x))
  expect_equal(colnames(l)[ncol(l)], "eventType")
})


test_that("Function linx_links_process() @ L405", {
  
  x <- system.file("extdata/linx/tables/linx.links.tsv.gz", package = "gpgr")
  (l <- linx_links_process(x))
  expect_equal(colnames(l)[ncol(l)], "ecDna")
})


test_that("Function linx_drivercatalog_process() @ L439", {
  
  x <- system.file("extdata/linx/tables/linx.driver.catalog.tsv.gz", package = "gpgr")
  (l <- linx_drivercatalog_process(x))
  expect_equal(colnames(l)[ncol(l)], "maxCopyNumber")
})


test_that("Function linx_drivers_process() @ L459", {
  
  x <- system.file("extdata/linx/tables/linx.drivers.tsv.gz", package = "gpgr")
  (l <- linx_drivers_process(x))
  expect_equal(colnames(l)[ncol(l)], "eventType")
})

