# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-20 18:16:40

context("File R/purple.R: @testexamples")

test_that("Function read_purple_cnv_gene() @ L21", {
  
  x <- system.file("extdata/purple/v2.39/purple.cnv.gene.tsv", package = "gpgr")
  read_purple_cnv_gene(x, "2.39")
  
  expect_equal(colnames(x)[ncol(x)], "minMinorAllelePloidy")
})

