# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-04-12 15:11:59

context("File R/sv.R: @testexamples")

test_that("Function split_double_col() @ L21", {
  
  x <- tibble::tibble(a = letters[1:10], b = paste0(round(runif(10), 2), ",", round(runif(10), 2)))
  (s <- gpgr:::split_double_col(x, b))
  
  expect_equal(colnames(s), c("a", "b1", "b2", "b"))
  expect_error(gpgr:::split_double_col(x, c))
  expect_equal(unname(sapply(s, class)), c("character", "numeric", "numeric", "numeric"))
})


test_that("Function count_pieces() @ L65", {
  
  (a <- gpgr:::count_pieces("foo,bar,baz", sep = ","))
  (b <- gpgr:::count_pieces("foo", sep = ","))
  (k <- gpgr:::count_pieces("", sep = ","))
  (m <- gpgr:::count_pieces(",", sep = ","))
  
  
  expect_equal(a, 3)
  expect_equal(b, 1)
  expect_equal(k, 0)
  expect_equal(m, 2)
  expect_error(gpgr:::count_pieces("foo", NA))
})


test_that("Function read_sv_tsv() @ L87", {
  
  x <- system.file("extdata/umccrise/v0.18/sv/manta.tsv", package = "gpgr")
  (sv <- read_sv_tsv(x))
  
  expect_equal(colnames(sv)[ncol(sv)], "MATEID")
  expect_error(read_sv_tsv(x, v = "0.17"))
})

