# Generated by roxytest: Do not edit by hand!
# Last updated: 2020-03-22 01:42:04

context("File R/purple.R: @testexamples")

test_that("Function read_purple_cnv_gene() @ L22", {
  
  x <- system.file("extdata/purple/v2.39/purple.cnv.gene.tsv", package = "gpgr")
  p <- read_purple_cnv_gene(x, "2.39")
  p
  
  expect_equal(colnames(p)[ncol(p)], "minMinorAllelePloidy")
  expect_error(read_purple_cnv_gene(x, "2.38"))
})


test_that("Function process_purple_cnv_gene() @ L78", {
  
  x <- system.file("extdata/purple/v2.39/purple.cnv.gene.tsv", package = "gpgr")
  g <- system.file("extdata/ref/umccr_cancer_genes_2019-03-20.tsv", package = "gpgr")
  pp <- process_purple_cnv_gene(x, g)
  
  expect_equal(colnames(pp)[ncol(pp)], "minRegSupportStartEndMethod")
  expect_error(process_purple_cnv_gene(x, "2.38"))
})

