# Generated by roxytest: do not edit by hand!

# File R/oncoviral.R: @testexamples

test_that("Function virusbreakend_summary_read() @ L18", {
  
  x <- system.file("extdata/virusbreakend/virusbreakend.vcf.summary.tsv", package = "gpgr")
  (vb <- virusbreakend_summary_read(x))
  expect_equal(colnames(vb)[ncol(vb)], "QCStatus")
})


test_that("Function virusbreakend_vcf_read() @ L101", {
  
  x <- system.file("extdata/virusbreakend/virusbreakend.vcf", package = "gpgr")
  (vb <- virusbreakend_vcf_read(x))
  expect_equal(colnames(vb)[ncol(vb)], "QC")
})

