# Generated by roxytest: do not edit by hand!

# File R/umccrise.R: @testexamples

test_that("Function pcgr_format_categories() @ L352", {
  (y <- pcgr_format_categories("N|intronic|difficult:80321"))
  (z <- pcgr_format_categories(c("N|intronic|difficult:80321", "2|impacts_other|giab_conf:5000")))
  expect_true(grepl("non-coding", y))
  expect_equal(length(strsplit(z, "\n")[[1]]), 2)
})
