# Generated by roxytest: Do not edit by hand!

context("File R/chord.R: @testexamples")

test_that("Function chord_run() @ L32", {
  
  
  snv <- system.file("extdata/umccrise/snv/somatic-ensemble-PASS.vcf.gz", package = "gpgr")
  sv <- system.file("extdata/umccrise/sv/manta.vcf.gz", package = "gpgr")
  chord_res <- chord_run(vcf.snv = snv, df.sv = gpgr:::chord_mantavcf2df(sv), sample.name = "foo")
  # chord_res <- chord_run(vcf.snv = snv, vcf.sv = sv, sample.name = "foo") # a bit slower
  
  expect_equal(length(chord_res), 2)
  expect_equal(names(chord_res), c("contexts", "prediction"))
  expect_equal(chord_res[["prediction"]][, 1, drop = TRUE], "foo")
})


test_that("Function chord_mantavcf2df() @ L93", {
  
  in_vcf <- system.file("extdata/umccrise/sv/manta.vcf.gz", package = "gpgr")
  d <- chord_mantavcf2df(in_vcf)
  
  expect_equal(d$sv_len[1], "-108")
  expect_equal(d$sv_type[1], "DEL")
})

