# Generated by roxytest: Do not edit by hand!

context("File R/hrdetect.R: @testexamples")

test_that("Function hrdetect_read_sv_vcf() @ L65", {
  
  x <- system.file("extdata/umccrise/v0.18/sv/manta.vcf.gz", package = "gpgr")
  sv_bedpe <- hrdetect_read_sv_vcf(x, nm = "SAMPLE")
  head(sv_bedpe)
  
  expect_equal(nrow(sv_bedpe), 190)
  expect_equal(colnames(sv_bedpe), c("chrom1", "start1", "end1", "chrom2",
               "start2", "end2", "sample", "strand1", "strand2"))
})

