# Generated by roxytest: Do not edit by hand!

# File R/linx_vis.R: @testexamples

test_that("Function linx_viscopynumber_read() @ L15", {
  
  x <- system.file("extdata/linx/tables/linx.vis_copy_number.tsv.gz", package = "gpgr")
  (l <- linx_viscopynumber_read(x))
  expect_equal(colnames(l)[ncol(l)], "BAF")
})


test_that("Function linx_visfusion_read() @ L41", {
  
  x <- system.file("extdata/linx/tables/linx.vis_fusion.tsv.gz", package = "gpgr")
  (l <- linx_visfusion_read(x))
  expect_equal(colnames(l)[ncol(l)], "FusedExonDown")
})


test_that("Function linx_visgeneexon_read() @ L71", {
  
  x <- system.file("extdata/linx/tables/linx.vis_gene_exon.tsv.gz", package = "gpgr")
  (l <- linx_visgeneexon_read(x))
  expect_equal(colnames(l)[ncol(l)], "ExonEnd")
})


test_that("Function linx_visproteindomain_read() @ L98", {
  
  x <- system.file("extdata/linx/tables/linx.vis_protein_domain.tsv.gz", package = "gpgr")
  (l <- linx_visproteindomain_read(x))
  expect_equal(colnames(l)[ncol(l)], "Info")
})


test_that("Function linx_vissegments_read() @ L124", {
  
  x <- system.file("extdata/linx/tables/linx.vis_segments.tsv.gz", package = "gpgr")
  (l <- linx_vissegments_read(x))
  expect_equal(colnames(l)[ncol(l)], "InDoubleMinute")
})


test_that("Function linx_vissvdata_read() @ L150", {
  
  x <- system.file("extdata/linx/tables/linx.vis_sv_data.tsv.gz", package = "gpgr")
  (l <- linx_vissvdata_read(x))
  expect_equal(colnames(l)[ncol(l)], "InDoubleMinute")
})

