package:
  name: r-gpgr
  version: 1.1.0 # bump2version

source:
  path: ../..

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - git
  host:
    - r-base
    - r-bedr
    - r-cli
    - r-dplyr
    - r-ggplot2
    - r-gt
    - r-gtools
    - r-jsonlite
    - r-readr
    - r-rlang
    - r-stringr
    - r-tidyr
    # suggests
    - r-argparse
    - r-details
    - r-devtools
    - r-dt
    - r-glue
    - r-kableExtra
    - r-knitr
    - r-patchwork
    - r-purrr
    - r-rmarkdown
    - r-scales
    - r-testthat
    - r-tibble
    - r-tidyselect

  run:
    - r-base
    - r-bedr
    - r-cli
    - r-dplyr
    - r-ggplot2
    - r-gt
    - r-gtools
    - r-jsonlite
    - r-readr
    - r-rlang
    - r-stringr
    - r-tidyr
    # suggests
    - r-argparse
    - r-details
    - r-devtools
    - r-dt
    - r-glue
    - r-kableExtra
    - r-knitr
    - r-patchwork
    - r-purrr
    - r-rmarkdown
    - r-scales
    - r-testthat
    - r-tibble
    - r-tidyselect

test:
  commands:
    - $R -e "library('gpgr')"

about:
  home: https://github.com/umccr/gpgr
  license: MIT + file LICENSE
  summary: Genomics Platform Group Reporting
  license_family: MIT
